feat: добавлены класс User и Film                                    …
Fenris06/java-filmorate pull request #1
Opened 2023-02-02 19:12 UTC by Fenris06

…           feat: добавлены классы Filmcontrollers и Usercontrollers                        feat: добавлен класс ValidationExaption                                         feat: добавлен класс Validation                                                 Test: протестирован класс Validation

2023-02-02 20:03 UTC, Fenris06 commented
Первый pull reqvest

2023-02-02 20:21 UTC, Fenris06 commented
Первый pull reqvest

2023-02-03 21:32 UTC, ohelly requested changes
Привет! Отличная работа, в целом все работает корректно за исключением некоторых моментов, их необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.

Также рекомендую сделать валидацию некоторых полей, например дату релиза фильма, и поле логин у пользователя, с помощью своих собственных аннотаций, это будет полезно, так как аннотации частенько приходится писать.

2023-02-03 21:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Рекомендация: Для полей идентификаторов лучше использовать классы обертки: Long или Integer, так как они могут быть null, а примитивные типы по дефолту равны нулю.

Рекомендация также относится и к модели User

2023-02-03 21:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
Рекомендация: Для логгера также можно использовать lombok: аннотация ``@Slf4j`` добавит поле, которое будет доступно также по полю log.

2023-02-03 21:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(Validation.getValidateFilmDate())) {
Необходимо исправить: Нет проверки на то, что releaseDate у фильма может быть null, если отправить запрос на создание фильма без указания даты то приложение выкинет NullPointerException.'

Аналогичная проблема в методе обновления

2023-02-03 21:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if(user.getLogin().contains(" ")) {
Необходимо исправить: "Пробельные" символы это не только пробел, также к ним можно отнести перенос строки, табуляцию и другие. Вместе они называются whitespace. Поэтому необходимо данную валидацию доработать, рекомендую использовать регулярное выражение.

Такая же проблема в методе обновления

2023-02-03 21:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Необходимо исправить: Также необходимо добавить проверку на то, что !name.isEmpty()

2023-02-03 21:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName().isBlank()) {
Необходимо исправить: А здесь необходимо добавить проверку на то, что name != null

2023-02-03 21:32 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/ValidationTest.java
> +public class ValidationTest {
Необходимо исправить: Тесты написаны немного неправильно, они проверяют самописные методы валидации, которые не используются вне тестов. Необходимо переписать тесты и использовать например mockMvc: 
https://sysout.ru/testirovanie-kontrollerov-s-pomoshhyu-mockmvc/

2023-02-06 12:25 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Исправил!

2023-02-06 12:25 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
Решил пока оставит так как есть!

2023-02-06 17:44 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(Validation.getValidateFilmDate())) {
Добавил к полую releaseDate класса Film аннотацию @NotNull.

2023-02-06 17:55 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if(user.getLogin().contains(" ")) {
Свою аннотацию пока не поучилось написать. Реализовал дополнительный метод валидации isLoginUserValidation c проверкой на пробельный символ через регулярное выражение.

2023-02-06 20:13 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Добавил проверку IsBlank(). На сколько я понял ее отличие от IsEpmpy() в том что она дополнительно проверяет на пробел.

2023-02-06 20:14 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName().isBlank()) {
На проверку на null

2023-02-07 10:15 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName().isBlank()) {
В тоги решил сделать отдельны метод в классе валидации.

2023-02-07 10:17 UTC, Fenris06 commented on src/test/java/ru/yandex/practicum/filmorate/ValidationTest.java
> +public class ValidationTest {
Тесты исправил.

2023-02-07 10:52 UTC, Fenris06 commented
Привет спасибо за ревью. Хотел протестировать целиком контроллеры, но так и не получилось разобраться. Протестировал отдельно валидацию Spring boot и свою кастомную.  Если не сложно можешь еще каких-нибудь ссылок накидать по тестированию Api и по написанию своих валидаций в Spring boot.

2023-02-07 19:50 UTC, ohelly requested changes
Привет! Исправлены все замечания, все работает корректно, но необходимо поправить тесты, ниже опишу почему и как.

Сейчас тесты проверяют методы ``isFilmValidation`` и ``isUserValidation`` из класса Validation, но это неверный подход, потому что данные методы не используются в контроллерах, то есть проверка в контроллерах происходит другим путем, отличным от того, который проверяется в тестах. Задача тестов воспроизвести реальную работу приложения.

Реальная работа: Приложение запущено и на него шлются http запросы(с помощью Postman'a или браузера).
Следовательно, в тестах мы тоже должны посылать запросы на наши контроллеры, чтобы воспроизвести реальную работу. Для этого можно использовать mockMvc, о котором я кидал ссылку в прошлый раз, ее в принципе должно хватить на текущем спринте. Если будут вопросы то пиши в пачке, постараюсь помочь.

В тестах также проверяются методы ``isFilmReleaseDateValidation`` и ``isLoginUserValidation`` и это уже правильные тесты, так как они проверяют реальные методы, которые работают и в контроллерах. Но этого недостаточно, так как у нас есть и другие проверки, которые выполняются не методами, а аннотациями и их тоже следует тестировать.

О том, как создать свои собственные аннотации для проверок можно почитать тут: https://www.logicbig.com/tutorials/java-ee-tutorial/bean-validation/create-custom-constraint.html

Также в случае вопросов можешь обратиться ко мне в Пачку.

2023-02-07 19:50 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
Рекомендация: В данном классе идентификатор лучше тоже заменить на класс обертку

2023-02-07 19:50 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/validation/Validation.java
> +package ru.yandex.practicum.filmorate.validation;
Необходимо исправить: Тесты все же будет лучше переработать, подробнее описал в комменте пул реквеста

2023-02-10 18:03 UTC, Fenris06 commented
Все тесты контроллеров пришлось закинуть в один класс. В нем оставил комментарии к проблемам которые возникли.

2023-02-10 18:41 UTC, Fenris06 commented
Извини что так много коммитов. Решил попробовать запушить через идею новую версию и все пошло наперекосяк. В итоги GitHub заглючил и пришлось откатывать все. А потом он всетаки прогрузил первоначальную версию и уже пришлось ее мержить с тем что я на откатывал. В общем отпало желание пользоваться идеей для отправки на github).

2023-02-10 18:50 UTC, Fenris06 commented
> Извини что так много коммитов. Решил попробовать запушить через идею новую версию и все пошло наперекосяк. В итоги GitHub заглючил и пришлось откатывать все. А потом он всетаки прогрузил первоначальную версию и уже пришлось ее мержить с тем что я на откатывал. В общем отпало желание пользоваться идеей для отправки на github).
По итогу все работает. И самое забавное в какойто момент у меня было два одинаковы класса для тестирования контроллеров и они оба работали. А отдельный класс для UseController нет.

2023-02-10 20:22 UTC, ohelly commented
> > Извини что так много коммитов. Решил попробовать запушить через идею новую версию и все пошло наперекосяк. В итоги GitHub заглючил и пришлось откатывать все. А потом он всетаки прогрузил первоначальную версию и уже пришлось ее мержить с тем что я на откатывал. В общем отпало желание пользоваться идеей для отправки на github).
> > По итогу все работает. И самое забавное в какойто момент у меня было два одинаковы класса для тестирования контроллеров и они оба работали. А отдельный класс для UseController нет.

Рекомендую все же разобраться с тем, как использовать идею для гита, можно видосики глянуть или официальную документацию. Создать собственный тестовый репозиторий и потренироваться, так как идея на самом деле предлагает очень удобный функционал к гиту, будет очень полезно если разберешься.

2023-02-10 20:43 UTC, ohelly approved these changes
Привет! Оставил рекомендации по тестам, жду их исправление к следующему спринту. Работу принимаю, удачи в дальнейшем обучении!

2023-02-10 20:43 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/NewUserControllerTest.java
> +/*Тесты в этом классе не получается запустить. Он сделан по аналогии с классом фильмов.
Рекомендация: Чтобы данный класс заработал необходимо добавить аннотацию над классом ``WebMvcTest``. Данная аннотация позволит поднять всю оболочку спринга, без нее он не мог заинжектить ObjectMapper и поэтому вылетал NullPointerException. Также советую научиться пользоваться дебаггером, в идее он есть, с помощью него можно было бы увидеть, где именно вылетает NPE.

2023-02-10 20:43 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/FilmAndUserControllerTest.java
> +           то айдишнк фильма будет произвольным образом менятся и тесты перестанут запускаться все вмести*/
На текущий момент это ок, в будущем, когда появятся дополнительные слои в приложении(контроллер-сервис-репозиторий) данный тест можно будет изменить.

2023-02-10 20:43 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/FilmAndUserControllerTest.java
> +//    public void shouldNotCustomValidationAddUserIfUserLoginHasSpaceAndEmpty() throws Exception{
В данном тесте проблем нет, проблема кроется в UserController. Сейчас объясню, как я к этому пришел:
1) Тест упал, но когда тест падает, он пишет в чем проблема, смотрим:
![image](https://user-images.githubusercontent.com/51891976/218192837-c739384f-8821-4784-9a7f-3be32e9d2448.png)
Ожидается одна ошибка, но пришла другая, поэтому тест и говорит, что он не прошел. Может показаться, что ошибки одинаковые, раз у них одинаковое название, но это не так, у них полное название разное. Полное название это пакет + название класса, поэтому тест и считает, что это разные результаты.

Далее идем в UserController и смотрим:
![image](https://user-images.githubusercontent.com/51891976/218193224-a477159c-2f8c-4b55-89a9-853ef107956e.png)
И видим, что мы оказывается выкидываем не нашу ошибку, которая находится в пакете ru.yandex.practicum.filmorate.exeption, а ошибку javax'a. Следовательно меняем импорт и тест проходит

Меняем это
![image](https://user-images.githubusercontent.com/51891976/218193440-79857562-1eb9-4c0a-88da-85dce5b7b2df.png)
На это
![image](https://user-images.githubusercontent.com/51891976/218193521-51b94639-8d0a-4438-acf9-86f71d81acde.png)

2023-02-13 17:26 UTC, merged