feat: добавлены одельные интерфейсы хранилища FilmStorage и          …
Fenris06/java-filmorate pull request #2
Opened 2023-02-19 23:14 UTC by Fenris06

…           UserStorage                                                                     feat: вся бизнесс логика вынесена в отделные классы FilmServis                  и UserServis                                                                    feat: добалена новая биснес логика по добавлению в друзья и до                  балению лайков фильмам.                                                         feat: добавлены новые конроллеры для вывода списка друзей и                     списка филмов по рейтингу лайков                                                feat: добавлен новый контроллер для перезвата исключений                        test; провеен рефакторинг тестов

2023-02-19 23:42 UTC, Fenris06 commented
Привет! Тесты подправил и сделал merge в main. В новой версии тесты переписал  с использованием TestRestTemplate (Мок не захотел запускаться). Единственное в тестах опять не получилось перехватить  исключения. Не получилось перехватить исключения которые выкидывает валидация спринга (хотел для них отдельный контроллер сделать). Если есть возможность можешь подсказать как это сделать(пробовал посмотреть в идеи какое исключение выкидывает каждая валидация но не смог найти). Хотел узнать твое мнение по поводу аннотации data. Пробовал сначала сделать через нее, но так и не получилось правильно инициализировать поле с листом для хранения лайков и друзей(поле всегда было null). Сделал через геттор и сеттор и все заработало. Слышал мнение что использование аннотация data плохая практика.

2023-02-20 23:58 UTC, ohelly requested changes
Привет! Отличная работа, есть небольшие замечания по работе, также оставил рекомендации на которые стоит обратить внимание.

Также есть замечание по тестам, которое подробно в них описал. + приложил пример как запустить тесты с mockMvc. С TestRestTemplate ошибка не отлавливается, потому что он работает по другому, он их не выкидывает, а оборачивает в ответ.

По поводу аннотации ``@Data``, да, ее лучше не использовать, если совместно с ней используются и другие аннотации ломбока. У нее часто возникают с ними конфликты, лучше обойтись без нее и перечислить просто вручную все аннотации, которые тебе неободимы.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(InMemoryFilmStorage.class);
Рекомендация: Для логирования можно использовать ломбок, выглядит это вот так, аннотация ``@Slf4j`` + log
![image](https://user-images.githubusercontent.com/51891976/220208399-ed36e639-faf9-4c65-988a-0600ad352f01.png)

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +        return films.get(film.getId());
Рекомендация: В данном случае не обязательно доставать фильм из хранилища, так как он будет ровно такой же, какой и пришел, поэтому можно просто вернуть тот фильм, который пришел как параметр в метод.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +        if (films.get(id) != null) {
Рекомендация: На строках 57, 58 и 59 выполняется три раза одно и то же действие. Если мы представим, что мы используем базу данных вместо хранилища в виде мапы, то это будет расходовать наши ресурсы(хотя даже в мапе, если она станет большой, это будет трудозатратно). Чтобы этого избежать можно просто достать фильм ``Film film = films.get(id);`` и дальше уже проверять, что ``film != null`` вывести его в лог и вернуть из метода.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +    public void setId(Integer id) {
Необходимо исправить: От данного метода лучше избавиться, так как не должно быть возможности задавать значение идентификатора, это может сломать логику. Понимаю что используется для тестов, но в комментарии к тестам напишу как это можно решить.

Аналогично и для метода deleteFilms.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/users/InMemoryUserStorage.java
> +    public void setId(Integer id) {
Необходимо исправить: Здесь также следует удалить методы setId и deleteUsers

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/users/InMemoryUserStorage.java
> +        setUserLoginValidation(user);
Необходимо исправить: Валидацию будет лучше вынести в слой сервиса. Хранилище обычно только сохраняет/достает/удаляет данные. Все проверки модели всегда в сервисе.

Также и для метода обновления.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Рекомендация: Вместо конструктора также можно использовать ломбок. Для этого нам поможет аннотация ``@RequiredArgsConstructor``, она создает конструктор для всех final полей. Выглядит это вот так и этот код будет прекрасно работать.
![image](https://user-images.githubusercontent.com/51891976/220209678-7154a5fa-0a16-43ee-bef2-b68bb9ffc18f.png)

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            if (userStorage.getUser(userId) != null) {
Рекомендация: Здесь следует сократить кол-во вызовов ``userStorage.getUser(userId)``. Сейчас их два, на 60  на 61 строке. Необходимо просто достать пользователя один раз вначале, а затем проверять его на null. Но вообще, в данном случае, эту проверку можно даже не делать, так как в userDbStorage уже есть такая проверка и если юзер не найден то выкинется эксепшен.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserStorage userStorage) {
Рекомендация: Аналогичная рекомендация про ломбок, также как и в UserService.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.sort(likeComparator);
Рекомендация: Советую почитать про такую штуку как Stream API в java, очень полезная вещь для работы с коллекциями. По началу может показаться сложновато, но быстро привыкаешь. С помощью них можно сократить данный метод вот так:
![image](https://user-images.githubusercontent.com/51891976/220210471-c239688d-9209-4742-88c3-a24e7f2f8da0.png)

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          if (!isFilmReleaseDateValidation(film)) {
Рекомендация: Валидацию входящей модели лучше вынести в сервисный слой. Контроллер обычно ничего не делает, кроме как вызова соответствующего метода сервиса.

Аналогично для метода обновления фильма. + также в UserController.

2023-02-20 23:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/exeption/CustomValidationException.java
> +public class CustomValidationException extends Exception {
Рекомендация: Исключения лучше наследовать от RuntimeException, тогда нам не придется добавлять throws в сигнатуру наших методов, например как сейчас сделано в контроллерах
![image](https://user-images.githubusercontent.com/51891976/220210853-60244ff8-95b1-4e86-bc2c-a54cae36dd27.png)

2023-02-20 23:58 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/NewFilmControllerTest.java
> +        filmStorage.deleteFilms();
Рекомендация: Для того чтобы избавиться от этих методов, мы в тестах не должны использовать filmStorage :)
Нам необходимо написать тесты для сервисов, то есть мы должны покрыть тестами наши сервисы, так как на них лежит основная логика. Ниже показал пример.

2023-02-20 23:58 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/NewUserControllerTest.java
> +    public void afterTest() {
Рекомендация: Для того чтобы избавиться от этих методов, мы в тестах не должны использовать userStorage :)
Нам необходимо написать тесты для сервисов, то есть мы должны покрыть тестами наши сервисы, так как на них лежит основная логика. Ниже показал пример.

2023-02-20 23:58 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/NewUserControllerTest.java
> +    public void shouldUserControllerUpdateUserIfAllFieldsAreCorrect() {
Данный тест можно переписать следующим образом: 
![image](https://user-images.githubusercontent.com/51891976/220212805-de395ee3-f4f8-414e-81b4-702b4f18a8c0.png)

2023-02-20 23:58 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/NewFilmControllerTest.java
> +    public void shouldValidationPutFilmIfAllFieldsAreCorrect() {
Данный тест можно переписать следующим образом:
![image](https://user-images.githubusercontent.com/51891976/220213051-153cc917-5022-4a9d-ad99-4659762ce50e.png)

2023-02-20 23:58 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/NewFilmControllerTest.java
> +public class NewFilmControllerTest {
Необходимо исправить: Это общее замечание по тестам вместе с рекомендацией по ней.
Старайся не опираться на идентификаторы фильмов и юзеров при тестах, задача теста проверить какое то действие, какой идентификатор ему присвоится при добавлении нас не интересует, нас интересует, что фильм или юзер создался.

Тогда возникает вопрос, как тогда проверить, что контроллеры правильно валидируют наши данные? Покажу пример:
![image](https://user-images.githubusercontent.com/51891976/220214695-b7f8a692-6cae-4279-b18b-9b5b708f675f.png)

Здесь мы просто проверяем на то, что контроллеры успешно валидируют входящую модель, а не то, что они создают или не создают. Здесь наша задача проверить, что контроллер не пропустит неверную модель, а вернет ошибку.

2023-02-21 16:45 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(InMemoryFilmStorage.class);
Логи передела при помощи lombok. Действительно удобно.

2023-02-21 16:58 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +        if (films.get(id) != null) {
Пока не исправлял.

2023-02-21 17:15 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/exeption/CustomValidationException.java
> +public class CustomValidationException extends Exception {
Исправил.

2023-02-21 17:26 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/users/InMemoryUserStorage.java
> +        setUserLoginValidation(user);
Исправил

2023-02-21 17:31 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Исправил

2023-02-21 18:20 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +        return films.get(film.getId());
Исправил

2023-02-21 18:34 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            if (userStorage.getUser(userId) != null) {
Исправил.

2023-02-21 18:34 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserStorage userStorage) {
Исправил

2023-02-21 18:43 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.sort(likeComparator);
Исправил

2023-02-21 19:07 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          if (!isFilmReleaseDateValidation(film)) {
Исправил

2023-02-21 19:20 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +        if (films.get(id) != null) {
Исправил

2023-02-21 19:21 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +        return films.get(film.getId());
Исправил

2023-02-21 19:21 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(InMemoryFilmStorage.class);
Исправил

2023-02-23 21:46 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/InMemoryFilmStorage.java
> +    public void setId(Integer id) {
Убрал

2023-02-23 21:47 UTC, Fenris06 commented on src/main/java/ru/yandex/practicum/filmorate/storege/users/InMemoryUserStorage.java
> +    public void setId(Integer id) {
Убрал

2023-02-23 21:47 UTC, Fenris06 commented on src/test/java/ru/yandex/practicum/filmorate/NewFilmControllerTest.java
> +        filmStorage.deleteFilms();
Исправил

2023-02-23 21:48 UTC, Fenris06 commented on src/test/java/ru/yandex/practicum/filmorate/NewUserControllerTest.java
> +    public void afterTest() {
Исправил

2023-02-23 21:49 UTC, Fenris06 commented on src/test/java/ru/yandex/practicum/filmorate/NewFilmControllerTest.java
> +public class NewFilmControllerTest {
Исправил

2023-02-23 22:09 UTC, Fenris06 commented
Привет. Поправил твои замечания. Немного переписал тесты. Тесты Storage вынес в отдельные классы. Интересно что  в тестах filmStorag получилось метод get протестировать изолировано от остальных, а в userStorage он возвращает  юзеров из предыдущих тестов. Дополнительно протестировал userServis с библиотекой mocito. Вроде получилось.

2023-02-24 22:34 UTC, ohelly approved these changes
Привет! Отличная работа! Исправлены все замечания, а также написаны очень хорошие тесты. Работу принимаю, удачи в дальнейшем обучении!

2023-02-24 22:34 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/FilmStorageTest.java
> +public class FilmStorageTest {
Рекомендую также писать тесты с ошибочными случаями. Например тест, в котором пытаемся обновить фильм, которого не существует. Следовательно тест будет правильным если вылетит исключение.

2023-02-24 22:34 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/NewUserControllerTest.java
> +public class NewUserControllerTest {
Рекомендую добавить тестов на успешные операции. То есть сейчас все тесты в данном классе проверяют только ошибки, но также необходимо и проверять успешные случаи.

2023-02-24 22:34 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTest.java
> +        assertTrue(user.getFriends().contains(2));
Вместо цифр 1 и 2 лучше использовать переменные, которые описаны выше, userFirstId и userSecondId. Так понятнее что они означают, а также меньше шанс опечататься.

2023-02-25 09:12 UTC, merged