Add database
Fenris06/java-filmorate pull request #3
Opened 2023-03-20 02:16 UTC by Fenris06

2023-03-20 02:37 UTC, Fenris06 commented
Привет. Доставила мне проблем это задание. Долго не мог добавить несколько жанров к фильму.  Тесты как обычно доставляют боль и разочарование. Добавление и обновления тестяться нормально. Но стоит только попробовать получить какой-нибудь список начинаются проблемы с его размером. Самое забавное что тест на получение списка юзеров в идеи запускался нормально со всеми тестами. Когда добавлял в пулл реквест он вылетел и пришлось править его размер.  Правильная схема  базы лежит в мейне.

2023-03-20 21:03 UTC, ohelly requested changes
Привет! В целом отличная работа и в общем все работает корректно. Но есть несколько функциональных замечаний, которые необходимо поправить. Также оставил ряд рекомендаций.
По поводу проблем с тестами, то можешь написать в пачку с конкретным примером, так будет понятнее.

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int rate;
Рекомендация: Поле rate можно выпилить, больше нигде не используется. Вместо него теперь mpa.

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> -    private final Set<Integer> likes = new TreeSet<>();
А почему лайки были удалены?

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/FilmDbStorage.java
> +        String sqlQuery = "SELECT f.*, r.rate_name, g.genre_id, g.genre_name FROM films AS f JOIN rate AS r " +
Необходимо исправить: Жанры необходимо получать не здесь, а с помощью GenreDbStorage, но есть пара нюансов: Во-первых, получение жанров из их стораджа необходимо делать из FilmService. То есть, в FilmService вызываем FilmDbStorage, получаем все фильмы, а затем уже вызываем GenreService, который в свою очередь должен получать все жанры для фильмов.
Нюанс номер два: Все жанры должны запрашиваться из БД одним запросом независимо от количества фильмов. То есть пройтись циклом по всем фильмам и доставать жанры не выйдет. Чтобы этого достичь тебе может помочь HashMap и запрос с оператором IN.

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/FilmDbStorage.java
> +        Integer filmId = film.getId();
Рекомендация: Данный метод тоже лучше будет вынести в GenreDbStorage.

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/FilmDbStorage.java
> +                "LEFT JOIN (SELECT film_id, COUNT(user_id) AS film_likes FROM likes GROUP BY film_id) AS l " +
Необходимо исправить: Из данного метода также необходимо убрать получение жанров.

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/FilmDbStorage.java
> +        Map<Integer, Film> films = new HashMap<>();
Рекомендация: Если вынести получение жанров из данного класса, то в этом методе можно будет избавиться от мапы. Также рекомендую в данном методе оставить только формирование объекта Film, а само выполнение запроса оставить в методах выше. Вот пара примеров + выделил то, как можно выставлять параметры в запросах, вместо их склеивания к строке
![image](https://user-images.githubusercontent.com/51891976/226461487-b8d1434d-a898-44d7-91ba-2e699ec568f8.png)
![image](https://user-images.githubusercontent.com/51891976/226461590-a9f2bc42-3744-4dba-8b9d-c2fb6cf546e2.png)

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/films/FilmDbStorage.java
> +        jdbcTemplate.batchUpdate(addGenresQuery, new BatchPreparedStatementSetter() {
Здорово, что используется batch update!

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storege/users/UserDbStorage.java
> +public class UserDbStorage implements UserStorage {
А вот тут уже все корректно, примерно такого же и ожидаю в FilmDbStorage :)

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.setFilmLike(filmId, userId);
Необходимо исправить: Необходимо добавить проверки, что фильм и юзер с соответствующими идентификаторами существуют. Аналогично для метода обновления фильма и удаления лайка.

2023-03-20 21:03 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
Необходимо исправить: Для данного класса также стоит добавить явные проверки на то, существует ли пользователь в БД для методов addUserFriends, deleteUserFriends, getUserFriends и getCommonFriends. Также в первых двух методах отлавливается ексепшен и выкидывается NotFoundException, но Exception не всегда означает, что данных нет в БД, иногда это может быть SQL ошибка или ошибка подключения к БД. Поэтому так делать не стоит.

2023-03-21 21:06 UTC, ohelly approved these changes
Привет! Теперь все отлично, хорошая работа. Можно двигаться дальше, работу принимаю!

2023-03-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return getFilm(filmStorage.updateFilm(film).getId());
Рекомендация: Рекомендую все же избавить от getFilm на 62 строке, так как получается слишком много запросов. 2 в filmStorage(обнволение + получение) и здесь снова обновление. Понимаю, что getFilm используется для обогащения жанрами, но лучше обогатить его прям здесь, не вызывая метод getFilm

2023-03-22 18:47 UTC, merged